pom.xml, src/main/java/org/folio/edge/core/InstitutionalUserHelper.java, src/main/java/org/folio/edge/core/model/ClientInfo.java, src/main/java/org/folio/edge/core/security/AwsParamStore.java, src/main/java/org/folio/edge/core/security/EphemeralStore.java, src/main/java/org/folio/edge/core/security/SecureStore.java, src/main/java/org/folio/edge/core/security/VaultStore.java, src/test/java/org/folio/edge/core/EdgeVerticleTest.java, src/test/java/org/folio/edge/core/security/AwsParamStoreTest.java, src/test/java/org/folio/edge/core/security/EphemeralStoreTest.java, src/test/java/org/folio/edge/core/security/VaultStoreTest.java
The API Keys we're currently using are easy to guess.  They consist of a URL safe base64 encoding of the tenant ID.  So if you know the tenantId, you can easily generate the API Key.
There are a couple things we can do to improve this, that don't require much effort:
- Incorporate a username into the apiKey.  This could be the same as the tenantId or something different
- Incorporate some sort of clientId or salt into the apiKey.  
`apiKey = urlBase64( clientId + delim + tenantId + delim + username )`
The key into the secure store would then incorporate those three pieces of information as well.  
The benefit of doing this is that the clientId would only be known to us, so even if someone knew the tenantId, and was able to find or guess the institutional user's username, they would still …
=> API Key Improvements

pom.xml, src/main/java/org/folio/edge/core/InstitutionalUserHelper.java, src/main/java/org/folio/edge/core/cache/TokenCache.java, src/test/java/org/folio/edge/core/cache/TokenCacheTest.java
The key used by the token cache should incorporate the clientId portion of the apiKey to prevent a bad apiKey from using a cached token
=> token cache key should include clientId from apiKey

pom.xml, src/main/java/org/folio/edge/core/InstitutionalUserHelper.java, src/main/java/org/folio/edge/core/security/AwsParamStore.java, src/main/java/org/folio/edge/core/security/EphemeralStore.java, src/main/java/org/folio/edge/core/security/SecureStore.java, src/main/java/org/folio/edge/core/security/VaultStore.java, src/test/java/org/folio/edge/core/EdgeVerticleTest.java, src/test/java/org/folio/edge/core/security/AwsParamStoreTest.java, src/test/java/org/folio/edge/core/security/EphemeralStoreTest.java, src/test/java/org/folio/edge/core/security/VaultStoreTest.java
The original implementation would log an error and continue w/ an empty string for the password when one could not be obtained from the secure store.  This essentially pushed the responsibility of failing the request out to FOLIO.
Given that this will almost never work (empty passwords shouldn't be allowed anyway), we should just fail the request right then and there, before even making a request to FOLIO.
=> fast fail on missing password

pom.xml, src/main/java/org/folio/edge/core/Constants.java, src/main/java/org/folio/edge/core/Handler.java, src/main/java/org/folio/edge/core/utils/OkapiClient.java, src/test/java/org/folio/edge/core/EdgeVerticleTest.java
Develop a base Handler class that removes the need to deal with common/boilerplate code for:
* Verifying that required parameters are present 
* Obtaining required and optional parameters from the request
* Obtaining an OKAPI Token (via the TokenCache or logging in)
Convenience methods for proxying the response from FOLIO back to the original caller (in both success and failure scenarios) are provided.
Generic methods for various error responses are defined as well, and can be overridden to suite your specific needs.
=> Base Handler for code shared among all edge API requests

NEWS.md, pom.xml, src/main/java/org/folio/edge/core/Constants.java, src/main/java/org/folio/edge/core/EdgeVerticle2.java, src/test/java/org/folio/edge/core/ConstantsTest.java, src/test/java/org/folio/edge/core/EdgeVerticle2Test.java, src/test/java/org/folio/edge/core/utils/MappersTest.java
The existing `EdgeVerticle` creates a vertx object in its constructor. This causes the `AbstractVerticle` to lose its vertx, which is supplied by the launch script. The launch vertx has the context where the deployment options are provided to the verticle, so deployment options are not available with `EdgeVerticle`.
To get around this, `EdgeVerticle2` was created. The constructor no longer creates a vertx and all operations are now done in the verticle `start` method using the launch provided vertx instance. The `start` method is provided by the `AbstractVerticle` and we use this method to perform our potentially long setup operations (secure store loading, etc.) that could block the main thread. Other entry points to the verticle behave synchronously, so are not ideal for this purpose. …
=> Created EdgeVerticle2 that supports DeploymentOptions for config

src/main/java/org/folio/edge/core/Constants.java, src/main/java/org/folio/edge/core/EdgeVerticle2.java, src/test/java/org/folio/edge/core/EdgeVerticle2Test.java, src/test/java/org/folio/edge/core/ResponseCompressionTest.java
JIRA: EDGCOMMON-9 - "EdgeVerticle2: support of HttpServer Options"
- Support of HttpServer Options in the EdgeVerticle2 enabled
- Property "response_compression" introduced
=> EDGCOMMON-9: EdgeVerticle2: support of HttpServer Options

NEWS.md, README.md, pom.xml, src/assembly/assembly.xml, src/main/java/org/folio/edge/core/utils/test/MockOkapi.java, src/test/java/org/folio/edge/core/ApiKeyHelperTest.java, src/test/java/org/folio/edge/core/EdgeVerticle2Test.java, src/test/java/org/folio/edge/core/EdgeVerticleTest.java, src/test/java/org/folio/edge/core/ResponseCompressionTest.java, src/test/java/org/folio/edge/core/security/AwsParamStoreTest.java, src/test/java/org/folio/edge/core/security/SecureStoreFactoryTest.java, src/test/java/org/folio/edge/core/utils/OkapiClientTest.java, src/test/java/org/folio/edge/core/utils/test/MockOkapiTest.java, src/test/resources/log4j.properties
* EDGCOMMON-4: used dependency management in maven to lock all vertx dependencies to the same (latest) version
* EDGCOMMON-7: used a more general args4j dependency, instead of the maven-plugin dependency
* EDGCOMMON-11: no longer generate a fat jar since edge-common does not provide a main class to run
* EDGCOMMON-12: ensure tests that start servers wait for them to shutdown before moving on to another test
* EDGCOMMON-13: ensure an AWS region is set in the test since there can be cases where the AWS Java SDK cannot determine a default region, which causes an exception
* fixed an encoding warning in the build by setting the source encoding to UTF-8
* increased the timeout on tests to 10,000 milliseconds since there appears to be a long delay in DNS lookup that can be greater than 3 …
=> Fixes for several problems

pom.xml, src/assembly/assembly.xml
Used maven profiles to create OS dependent variables in order to store the assembly regex. This is to overcome the need to escape the '/' using a '\\' on Windows to make the assembly plugin work, however, the backslash causes nothing to be included on Unix. Now we can use both and only the right one will be active on the host os.
=> Fix for EDGCOMMON-17

README.md, src/main/java/org/folio/edge/core/Handler.java, src/main/java/org/folio/edge/core/InstitutionalUserHelper.java, src/main/java/org/folio/edge/core/model/ClientInfo.java, src/main/java/org/folio/edge/core/utils/ApiKeyUtils.java, src/test/java/org/folio/edge/core/EdgeVerticle2Test.java, src/test/java/org/folio/edge/core/EdgeVerticleTest.java, src/test/java/org/folio/edge/core/ResponseCompressionTest.java, src/test/java/org/folio/edge/core/utils/ApiKeyUtilsTest.java
[EDGCOMMON-18](https://issues.folio.org/projects/EDGCOMMON/issues/EDGCOMMON-18)
The current structure of API keys is based on salt, tenantID, and username separated by an underscore (`_`) delimiter.  This is problematic since the delim character could appear in either the tenantId or username.
Change the API key structure to use JSON, e.g.
`{"s":"ABCDEF12345","t":"diku","u":"diku_admin"}`
* ApiKeyUtils has been updated
* JSON annotations have been added to the ClientInfo class as needed for jackson mapping
* Unit tests have been updated as needed
* `clientId` has been renamed to `salt` through the code for consistency and to avoid confusion
=> EDGCOMMON-18 Change how API keys are structured

NEWS.md, pom.xml
[EDGCOMMON-18](https://issues.folio.org/browse/EDGCOMMON-18)
Releasing v2.0.0 in order to allow upcoming edge API releases to use the new API key structure.
=> EDGCOMMON-18 - Release 2.0.0

pom.xml, src/assembly/assembly.xml
Add missing dependencies to the API Key Utils Jar (CLI).  
[EDGCOMMON-19](https://issues.folio.org/browse/EDGCOMMON-19)
* Add the necessary packages to the assembly inclusion list
* Update the regex exclusion pattern in pom.xml
=> EDGCOMMON-19 - include missing dependencies in apiKeyUtils jar

src/main/java/org/folio/edge/core/utils/OkapiClient.java
Set the `HttpClientOption` to allow the client to request compression be used if supported by the server. This allows pass through compression headers to not cause the server to unexpectedly send compressed data to the client's handlers, since it will now be taken care of by the client prior to reaching the handler with this option set.
=> EDGCOMMON-20: enable HTTP client compression support

README.md, src/main/java/org/folio/edge/core/utils/OkapiClient.java, src/main/java/org/folio/edge/core/utils/OkapiClientFactory.java, src/test/java/org/folio/edge/core/utils/OkapiClientTest.java
Fix a memory leak in edge-common module.
Introduce a cache to store okapi clients.
jira: https://issues.folio.org/browse/EDGCOMMON-25
related: https://issues.folio.org/browse/EDGRTAC-33
=> EDGCOMMON-25: Introduce okapi client cache to fix a memory leak.

Jenkinsfile, pom.xml, src/test/java/org/folio/edge/core/ApiKeyHelperTest.java, src/test/java/org/folio/edge/core/EdgeVerticle2Test.java, src/test/java/org/folio/edge/core/EdgeVerticleTest.java, src/test/java/org/folio/edge/core/ResponseCompressionTest.java, src/test/java/org/folio/edge/core/utils/test/MockOkapiTest.java
Upgraded the library to build with Java 11. Rest Assured was also upgraded since the existing version uses a class that is not available in Java 11. Newer versions no longer use this class. Versions that include this fix have relocated the package, so imports needed to be updated. Actual code within tests was not impacted. No code was changed to take advantage of Java 11 features.
=> EDGCOMMON-28: Upgrade to Java 11

pom.xml, src/main/java/org/folio/edge/core/EdgeVerticle.java, src/main/java/org/folio/edge/core/EdgeVerticle2.java, src/main/java/org/folio/edge/core/Handler.java, src/main/java/org/folio/edge/core/InstitutionalUserHelper.java, src/main/java/org/folio/edge/core/cache/Cache.java, src/main/java/org/folio/edge/core/cache/TokenCache.java, src/main/java/org/folio/edge/core/security/AwsParamStore.java, src/main/java/org/folio/edge/core/security/EphemeralStore.java, src/main/java/org/folio/edge/core/security/SecureStoreFactory.java, src/main/java/org/folio/edge/core/security/VaultStore.java, src/main/java/org/folio/edge/core/utils/OkapiClient.java, src/main/java/org/folio/edge/core/utils/test/MockOkapi.java, src/main/java/org/folio/edge/core/utils/test/TestUtils.java, src/main/resources/log4j.properties, src/main/resources/log4j2.properties, src/test/java/org/folio/edge/core/ApiKeyHelperTest.java, src/test/java/org/folio/edge/core/EdgeVerticle2Test.java, src/test/java/org/folio/edge/core/EdgeVerticleTest.java, src/test/java/org/folio/edge/core/ResponseCompressionTest.java, src/test/java/org/folio/edge/core/cache/CacheTest.java, src/test/java/org/folio/edge/core/cache/TokenCacheTest.java, src/test/java/org/folio/edge/core/security/AwsParamStoreTest.java, src/test/java/org/folio/edge/core/security/EphemeralStoreTest.java, src/test/java/org/folio/edge/core/utils/ApiKeyUtilsTest.java, src/test/java/org/folio/edge/core/utils/OkapiClientTest.java, src/test/java/org/folio/edge/core/utils/test/MockOkapiTest.java, src/test/java/org/folio/edge/core/utils/test/TestUtilsTest.java
Note the the TestUtils.assertLogMessage implementation is incomplete. This utility was not tested before this PR and does not seem to be used anywhere (only in edge-common).
Tried compiling this branch with edge-patron. No changes needed to edge-patron code, except the pom update to use the snapshot.
=> Update log4j, mockito, restassured EDGCOMMON-23 EDGCOMMON-24

src/main/java/org/folio/edge/core/utils/OkapiClient.java, src/test/java/org/folio/edge/core/EdgeVerticleHttpTest.java, src/test/java/org/folio/edge/core/utils/OkapiClientTest.java
`edge-patron` relies on the OkapiHttpClient to fail with a `TimeoutException` in order to [provide a specific response to the client](https://github.com/folio-org/edge-patron/blob/f4a471d3f5ce861aae682bb2a8973dd5166c118c/src/main/java/org/folio/edge/patron/PatronHandler.java#L72-L73).
[Upgrading edge-patron](https://github.com/folio-org/edge-patron/pull/51/files) to Vert.x 4.x also meant upgrading to a version of edge-common that also uses vert.x 4.x (version 4.1.x or greater was used for testing)
Use the request timeout configuration (as suggested in the [vert.x documentation](https://vertx.io/docs/vertx-web-client/java/)) to produce a specific TimeoutException that can be handled specifically.
Changed the `EdgeVerticleHttpTest` to check for the more specific TimeoutException that using …
=> Use request timeout EDGCOMMON-36

pom.xml, src/main/java/org/folio/edge/core/utils/OkapiClient.java
Make use of HTTP/1.x pooling and keep alive, HTTP/1.1 pipe-lining, and HTTP/2 multiplexing as supported by WebClient based on HttpClient: https://vertx.io/docs/vertx-core/java/#_http1_x_pooling_and_keep_alive
For a high number of tenants (for example GBV) this will drastically reduce the number of HTTP connections and will reduce the latency resulting from establishing new connections.
=> EDGCOMMON-45: Reuse WebClient for pooling, pipe-lining, multiplexing

pom.xml, src/main/java/org/folio/edge/core/InstitutionalUserHelper.java, src/main/java/org/folio/edge/core/utils/OkapiClient.java, src/main/java/org/folio/edge/core/utils/test/MockOkapi.java, src/test/java/org/folio/edge/core/InstitutionalUserHelperTest.java, src/test/java/org/folio/edge/core/utils/OkapiClientTest.java
Remove any usage of the
me.escoffier.vertx:vertx-completable-future = https://github.com/cescoffier/vertx-completable-future
library because it is no longer maintained and doesn't work with Vert.x 4.
For details see https://issues.folio.org/browse/FOLREL-547
=> EDGCOMMON-48: Remove vertx-completable-future for Morning Glory

src/main/java/org/folio/edge/core/utils/OkapiClient.java, src/test/java/org/folio/edge/core/utils/OkapiClientTest.java
Fix the bug where the X-Okapi-Tenant header in the request overwrites
the configured X-Okapi-Tenant header in the response.
=> EDGCOMMON-47: Fix behavior when tenant header is present in a request

src/main/java/org/folio/edge/core/utils/test/MockOkapi.java, src/test/java/org/folio/edge/core/EdgeVerticleHttpTest.java, src/test/java/org/folio/edge/core/ResponseCompressionTest.java, src/test/java/org/folio/edge/core/utils/OkapiClientTest.java, src/test/java/org/folio/edge/core/utils/test/MockOkapiTest.java
Steps to Reproduce:
https://github.com/folio-org/edge-oai-pmh/blob/3ccabce4dd9a81dc4f7ce792956c4b4aac3a6496/src/test/java/org/folio/edge/oaipmh/utils/OaiPmhMockOkapi.java
Expected Results:
MockOkapi can be used with JUnit 5 and Junit 4.
MockOkapi#start and MockOkapi#close allow to .compose multiple Futures:
mockOkapi.start()
.compose(x -> startFooService())
.onComplete(context.asyncAssertSuccess());
Actual Results:
If pom.xml doesn't add the Junit 4 vertx-unit dependency the test will fail because MockOkapi requires Junit 4 vertx-unit in start and close method:
public void start(TestContext context)
public void close(TestContext context)
Cannot use a JUnit 5 VertxTestContext with start or close.
Neither start nor close allow to compose multiple Futures.
Solution:
Futurize MockOkapi#start …
=> EDGCOMMON-51: Futurize MockOkapi for Junit 5 and .compose

src/main/java/org/folio/edge/core/utils/OkapiClient.java, src/main/java/org/folio/edge/core/utils/test/MockOkapi.java, src/test/java/org/folio/edge/core/ResponseCompressionTest.java
Enable HTTP compression support (deflate, gzip) for the response from mod-x to edge-x.
There are two completely independent HTTP connections:
a) external client <-> edge-x, edge-x uses compression if external client sends "Accept-Encoding" HTTP header.
b) edge-x <-> mod-x, mod-x uses compression if edge-x sends "Accept-Encoding" HTTP header.
The two HTTP connections may use different compression algorithms, as set in the "Accept-Encoding" header.
This pull request is about b).
It is wrong if edge-x passes on the Accept-Encoding header from external client to mod-x. This needs to be fixed in the edge-x modules.
=> EDGCOMMON-52: Enable "Accept-Encoding: deflate, gzip" by default

src/main/java/org/folio/edge/core/Handler.java, src/main/java/org/folio/edge/core/utils/test/MockOkapi.java, src/test/java/org/folio/edge/core/utils/OkapiClientTest.java
Deprecate MockOkapi's X-Duration header. For security an edge module
should not pass any headers from the external client to the back-end
module unless strictly needed.
Provide MockOkapi.setDelay as a replacement for X-Duration.
Fix timeout reporting (HTTP 408 response code) by also checking
if Throwable.getCause() is instanceof TimeoutException.
=> EDGCOMMON-53: Deprecate X-Duration, provide setDelay, fix timeout msg

src/main/java/org/folio/edge/core/EdgeVerticleCore.java, src/test/java/org/folio/edge/core/EdgeVerticleCoreTest.java
Test against ConnectException, not against
error message "Connection refused" that is
"Verbindungsaufbau abgelehnt" in German locale.
In getProperties reduce complexity: Extract code
into createInputStream to avoid nested try clauses,
use guard clause to avoid if clause nesting.
Fix log level.
Replace compose by map in initializeSecureStore Future.
=> Code cleanup in EdgeVerticleCore

pom.xml
Vert.x 4.3.0 and 4.3.1 have this regression: They disable SSL in WebClient.
Vert.x >= 4.3.2 has a fix.
https://issues.folio.org/browse/EDGCOMMON-54
=> EDGCOMMON-54: Vert.x 4.3.3 fixing disabled SSL in 4.3.0/4.3.1

src/main/java/org/folio/edge/core/utils/OkapiClient.java, src/test/java/org/folio/edge/core/utils/OkapiClientTest.java
[EDGCOMMON-67](https://issues.folio.org/browse/EDGCOMMON-67): Provide a consortia-level access point/mechanism for retrieving patron data
**Approach**
Constructor-level changes are done for adding secondaryTenantId in OkapiClient.java class.
=> Provide a consortia-level access point/mechanism for retrieving patron data

README.md, src/main/java/org/folio/edge/core/Constants.java, src/main/java/org/folio/edge/core/EdgeVerticleHttp.java, src/main/java/org/folio/edge/core/utils/OkapiClient.java, src/main/java/org/folio/edge/core/utils/OkapiClientFactory.java, src/main/java/org/folio/edge/core/utils/OkapiClientFactoryInitializer.java, src/main/java/org/folio/edge/core/utils/SslConfigurationUtil.java, src/test/java/org/folio/edge/core/EdgeVerticleSslTest.java, src/test/java/org/folio/edge/core/OkapiClientInitializerTest.java, src/test/java/org/folio/edge/core/utils/OkapiClientFactoryTest.java, src/test/java/org/folio/edge/core/utils/OkapiClientTest.java
- Document things better
- Change keyCertOptions to trustStoreOptions for configuring Web Clients
- Make trustStoreOptions as optional for  configuring Web Clients
- Introduce OkapiClientFcatoryIntializer that allows to delete factories from all edge-modules. Logic to create okapi clients will be -encapsulated only in edge-common
Usages of these changes:
https://github.com/folio-org/edge-orders/pull/74/files
https://github.com/folio-org/edge-rtac/pull/68
https://github.com/folio-org/edge-lti-courses/pull/28/files
https://github.com/folio-org/edge-patron/pull/111/files
https://github.com/folio-org/edge-oai-pmh/pull/115/files
https://github.com/folio-org/edge-ncip/pull/40/
=> EDGCOMMON-79. Add truststore options to configure Web Clients

NEWS.md, pom.xml
Releasing these stories
* [EDGCOMMON-80](https://folio-org.atlassian.net/browse/EDGCOMMON-80) - Vert.x 4.5.7, Netty 4.1.108.Final fixing form post OOM CVE-2024-29025 
* [EDGCOMMON-78](https://folio-org.atlassian.net/browse/EDGCOMMON-78) - Enhance HTTP Endpoint Security with TLS and FIPS-140-2 Compliant Cryptography
* [EDGCOMMON-77](https://folio-org.atlassian.net/browse/EDGCOMMON-77) - Support HTTPS in OkapiClient, SSL
=> Release v4.7.0

pom.xml, src/main/java/org/folio/edge/core/security/AwsParamStore.java, src/main/java/org/folio/edge/core/utils/OkapiClient.java, src/test/java/org/folio/edge/core/security/AwsParamStoreTest.java
When working in the strict FIPS mode only approved SecureRandom instances may be used.
When creating AwsParamStore, AWSSimpleSystemsManagementClientBuilder must be configured with the appropriate SecureRandom instance.
=> Configure approved SecureRandom in FIPS mode
