README.md, pom.xml, src/main/java/org/folio/edge/core/utils/test/MockOkapi.java
=> FOLIO-398 tidy 1

pom.xml, src/main/java/org/folio/edge/core/Handler.java, src/main/java/org/folio/edge/core/InstitutionalUserHelper.java, src/main/java/org/folio/edge/core/utils/ApiKeyUtils.java, src/test/java/org/folio/edge/core/EdgeVerticleTest.java, src/test/java/org/folio/edge/core/utils/ApiKeyUtilsTest.java
Adding utilities for generating and parsing API keys, including a CLI.
=> API Key Utils

pom.xml, src/main/java/org/folio/edge/core/Constants.java, src/main/java/org/folio/edge/core/utils/OkapiClient.java, src/test/java/org/folio/edge/core/utils/OkapiClientTest.java
Cleanup how OkapiClient manages default and override request headers
=> Cleanup header handling

pom.xml, src/main/java/org/folio/edge/core/Constants.java, src/main/java/org/folio/edge/core/Handler.java, src/test/java/org/folio/edge/core/EdgeVerticleTest.java
Add a separate hook for invalid/missing api key.
=> Invalid api key

pom.xml, src/main/java/org/folio/edge/core/InstitutionalUserHelper.java, src/main/java/org/folio/edge/core/utils/OkapiClient.java, src/main/java/org/folio/edge/core/utils/test/MockOkapi.java
https://issues.folio.org/browse/EDGCOMMON-2
=> Use Verx-Completable-Future

NEWS.md, README.md, pom.xml, src/main/java/org/folio/edge/core/ApiKeyHelper.java, src/main/java/org/folio/edge/core/Constants.java, src/main/java/org/folio/edge/core/EdgeVerticle.java, src/main/java/org/folio/edge/core/Handler.java, src/test/java/org/folio/edge/core/ApiKeyHelperTest.java, src/test/java/org/folio/edge/core/EdgeVerticleTest.java
See [EDGCOMMON-1](https://issues.folio.org/browse/EDGCOMMON-1) for details.
=> Make the source of the API Key configurable

pom.xml, src/main/java/org/folio/edge/core/utils/OkapiClient.java, src/main/java/org/folio/edge/core/utils/test/MockOkapi.java, src/test/java/org/folio/edge/core/utils/OkapiClientTest.java
see [EDGCOMMON-3](https://issues.folio.org/projects/EDGCOMMON/issues/EDGCOMMON-3)
=> Don't include API Key Header in proxied requests

NEWS.md, pom.xml, src/main/java/org/folio/edge/core/security/EphemeralStore.java, src/main/resources/ephemeral.properties, src/test/java/org/folio/edge/core/security/EphemeralStoreTest.java
- Changes related to ephemeral.properties records format introduced;
- Artifact version changed to 0.3.8-SNAPSHOT;
- EphemeralStoreTest.java modified to support record format **{tenant}={user},{password}** instead of previously used **{tenant}={password}**.
=> EDGOAIPMH-8: - "OAI-PMH: Response compression" (EphemeralStore changes)

NEWS.md, pom.xml
=> Tmp release 1.0.0

NEWS.md, pom.xml
Patch release containing fix for ApiKeyUtils.jar (CLI)
[EDGCOMMON-19](https://issues.folio.org/browse/EDGCOMMON-19)
=> EDGCOMMON-19 release 2.0.1

pom.xml
=> Tmp release 2.0.3

README.md, src/main/java/org/folio/edge/core/Handler.java, src/main/java/org/folio/edge/core/InstitutionalUserHelper.java, src/main/java/org/folio/edge/core/cache/Cache.java, src/main/java/org/folio/edge/core/cache/TokenCache.java, src/main/java/org/folio/edge/core/security/EphemeralStore.java, src/main/java/org/folio/edge/core/utils/ApiKeyUtils.java, src/main/java/org/folio/edge/core/utils/test/MockOkapi.java, src/main/java/org/folio/edge/core/utils/test/TestUtils.java, src/test/java/org/folio/edge/core/utils/test/MockOkapiTest.java, src/test/java/org/folio/edge/core/utils/test/TestUtilsTest.java
These are minor suggested changes, reported by IntelliJ IDEA.
=> Remove unused NoCredentialsDefinedException; spell fixes; simplify

src/test/java/org/folio/edge/core/EdgeVerticle2Test.java, src/test/java/org/folio/edge/core/EdgeVerticleTest.java, src/test/java/org/folio/edge/core/security/AwsParamStoreTest.java
=> Avoid deprecated org.mockito.Matchers.any

src/main/java/org/folio/edge/core/EdgeVerticle.java, src/main/java/org/folio/edge/core/EdgeVerticle2.java
Deprecate now for 3.1 series.. Remove it, before 4.0 release.  EDGCOMMON-5 part 1.
=> Deprecated EdgeVerticle

NEWS.md, pom.xml
And 4.0.0-SNAPSHOT is next in line for master
=> Release 3 1 0

pom.xml, src/main/java/org/folio/edge/core/Constants.java, src/main/java/org/folio/edge/core/EdgeVerticle.java, src/main/java/org/folio/edge/core/EdgeVerticle2.java, src/main/java/org/folio/edge/core/Handler.java, src/main/java/org/folio/edge/core/utils/OkapiClient.java, src/main/java/org/folio/edge/core/utils/OkapiClientFactory.java, src/main/java/org/folio/edge/core/utils/test/MockOkapi.java, src/test/java/org/folio/edge/core/ApiKeyHelperTest.java, src/test/java/org/folio/edge/core/EdgeVerticle2Test.java, src/test/java/org/folio/edge/core/EdgeVerticleTest.java, src/test/java/org/folio/edge/core/security/AwsParamStoreTest.java, src/test/java/org/folio/edge/core/utils/OkapiClientFactoryTest.java, src/test/java/org/folio/edge/core/utils/OkapiClientTest.java
Based on EDGCOMMON-28 PR (that one should be merged before this one).
This PR will not be merged until https://github.com/folio-org/edge-common/pull/39 is merged. But comments are of course welcomed.
=> Update to Vert.x 4 EDGCOMMON-30

NEWS.md, pom.xml
https://issues.folio.org/browse/EDGCOMMON-41
=> Release 4.2.2

pom.xml, src/main/java/org/folio/edge/core/security/SecureStore.java, src/test/java/org/folio/edge/core/security/VaultStoreContainerTest.java
Use executeBlocking running on a worker thread so that the
event loop doesn't gets blocked.
=> EDGCOMMON-21: SecureStore#lookup = futurized get

pom.xml
Switched to the release version of folio-tls-utils dependency.
=> Switched to the release version of folio-tls-utils dependency.

NEWS.md, pom.xml, src/main/java/org/folio/edge/core/security/AwsParamStore.java, src/main/java/org/folio/edge/core/utils/OkapiClient.java, src/test/java/org/folio/edge/core/security/AwsParamStoreTest.java
Release bug fix for Quesnelia with adding support of SecureRandom in FIPS mode
https://folio-org.atlassian.net/browse/EDGCOMMON-82
=> [EDGCOMMON-82] Release Quesnelia v4.7.1

pom.xml, src/main/java/org/folio/edge/core/utils/OkapiClient.java
Hostname verification enabled for Http Clients when using TLS connections
=> Hostname verification enabled for Http Clients when using TLS connections

NEWS.md, pom.xml, src/main/java/org/folio/edge/core/utils/OkapiClient.java
Purpose:
https://folio-org.atlassian.net/browse/EDGCOMMON-83
=> Release 4.7.2 with enabling Hostname verification enabled for Http Clients when using TLS connections

pom.xml
Fix folio-tls-utils dependency.
=> Fix folio-tls-utils dependency.

NEWS.md, pom.xml
https://folio-org.atlassian.net/browse/EDGCOMMON-94
=> EDGCOMMON-94 release 5.0.0 for trillium
